[main]
font = code:size=16:fontfeatures=calt=0:fontfeatures=ss02=1
terminal = 'footclient -a _float'
lines = 12
width = 30
line-height = 40
# match-counter = yes

[border]
width = 4
radius = 40

[colors]

# Light Theme
# background = d0e0d8d8
# text = 405048ff
# prompt = 607068ff
# input = 405048ff
# match = 20a060ff
# selection = ffffff40
# selection-text = 203028ff
# selection-match = 20a060ff
# counter = 809088ff
# border = 90b0a0d8

# Dark Theme
background = 303834e8
text = a0a8a4ff
prompt = 809088ff
input = a0a8a4ff
match = 90f0c0ff
selection = ffffff20
selection-text = d0e0d8ff
selection-match = 90f0c0ff
counter = 809088ff
border = 586860e8
