root: /home/novi/.confast
ignored:
- .git
- .gitignore
- README.md
- scripts
files:
  confast: .config/confast
  environment.d: .config/environment.d
  fontconfig: .config/fontconfig
  foot: .config/foot
  fuzzel: .config/fuzzel
  mako: .config/mako
  mihu/global_override.yaml: .config/mihu/global_override.yaml
  misc/electron-flags.conf: .config/electron-flags.conf
  misc/htoprc: .config/htop/htoprc
  misc/hyfetch.json: .config/hyfetch.json
  misc/mimeapps.list: .config/mimeapps.list
  misc/qq-electron-flags.conf: .config/qq-electron-flags.conf
  misc/tealdeer.toml: .config/tealdeer/config.toml
  mpd: .config/mpd
  mpv: .config/mpv
  ncdu: .config/ncdu/config
  niri: .config/niri
  paru.conf: .config/paru/paru.conf
  rime/default.custom.yaml: .local/share/fcitx5/rime/default.custom.yaml
  rime/rime_frost.custom.yaml: .local/share/fcitx5/rime/rime_frost.custom.yaml
  rmpc: .config/rmpc
  waybar: .config/waybar
  yazi.toml: .config/yazi/yazi.toml
  zprofile: .zprofile
  zshrc: .zshrc
