# UI

input-default-bindings=no
input-builtin-bindings=no
osd-duration=3000
osd-font=monospace
osd-font-size=16
screenshot-format=webp
screenshot-webp-lossless=yes
screenshot-template="%F_%P"
screenshot-dir=~/Pictures/mpv

# Video

vo=gpu-next
gpu-api=vulkan
hwdec=auto
deband=yes
deband-iterations=2
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
dscale=ewa_lanczossharp
scale-antiring=0.7
cscale-antiring=0.7
dscale-antiring=0.7

# Subtitles

sub-ass-use-video-data=aspect-ratio
sub-file-paths-add=".:sub:subs:subtitle:subtitles"
sub-file-paths-append="/mnt/nfs/local/subtitles/movies"
sub-file-paths-append="/mnt/nfs/local/subtitles/movies/Black Mirror"
sub-file-paths-append="/mnt/nfs/local/subtitles/movies/Breaking Bad"
sub-file-paths-append="~/.cache/subtitles.link"

# Profiles

[high]
profile-restore=copy
glsl-shaders-clr=yes
glsl-shaders-append="~~/shaders/FSRCNNX_x2_16-0-4-1.glsl"
glsl-shaders-append="~~/shaders/FSRCNNX_x2_8-0-4-1.glsl"
# glsl-shaders-append="~~/shaders/CfL_Prediction.glsl"
glsl-shaders-append="~~/shaders/KrigBilateral.glsl"
glsl-shaders-append="~~/shaders/SSimDownscaler.glsl"
glsl-shaders-append="~~/shaders/adaptive-sharpen.glsl"

[anime-high-artcnn]
profile-restore=copy
glsl-shaders-clr=yes
glsl-shaders-append="~~/shaders/ArtCNN_C4F32_DS.glsl"
# glsl-shaders-append="~~/shaders/CfL_Prediction.glsl"
glsl-shaders-append="~~/shaders/KrigBilateral.glsl"
glsl-shaders-append="~~/shaders/SSimDownscaler.glsl"
glsl-shaders-append="~~/shaders/Anime4K/Deblur/Anime4K_Deblur_DoG.glsl"

[anime-high-a4k-1080p]
profile-restore=copy
glsl-shaders-clr=yes
glsl-shaders-append="~~/shaders/Anime4K/Restore/Anime4K_Clamp_Highlights.glsl"
glsl-shaders-append="~~/shaders/Anime4K/Restore/Anime4K_Restore_CNN_VL.glsl"
glsl-shaders-append="~~/shaders/Anime4K/Upscale/Anime4K_Upscale_CNN_x2_VL.glsl"
glsl-shaders-append="~~/shaders/Anime4K/Restore/Anime4K_Restore_CNN_M.glsl"
glsl-shaders-append="~~/shaders/Anime4K/Upscale/Anime4K_AutoDownscalePre_x2.glsl"
glsl-shaders-append="~~/shaders/Anime4K/Upscale/Anime4K_AutoDownscalePre_x4.glsl"
glsl-shaders-append="~~/shaders/Anime4K/Upscale/Anime4K_Upscale_CNN_x2_M.glsl"
glsl-shaders-append="~~/shaders/Anime4K/Deblur/Anime4K_Deblur_DoG.glsl"
glsl-shaders-append="~~/shaders/SSimDownscaler.glsl"

[anime-high-a4k-720p]
profile-restore=copy
glsl-shaders-clr=yes
glsl-shaders-append="~~/shaders/Anime4K/Restore/Anime4K_Clamp_Highlights.glsl"
glsl-shaders-append="~~/shaders/Anime4K/Restore/Anime4K_Restore_CNN_Soft_VL.glsl"
glsl-shaders-append="~~/shaders/Anime4K/Upscale/Anime4K_Upscale_CNN_x2_VL.glsl"
glsl-shaders-append="~~/shaders/Anime4K/Restore/Anime4K_Restore_CNN_Soft_M.glsl"
glsl-shaders-append="~~/shaders/Anime4K/Upscale/Anime4K_AutoDownscalePre_x2.glsl"
glsl-shaders-append="~~/shaders/Anime4K/Upscale/Anime4K_AutoDownscalePre_x4.glsl"
glsl-shaders-append="~~/shaders/Anime4K/Upscale/Anime4K_Upscale_CNN_x2_M.glsl"
glsl-shaders-append="~~/shaders/Anime4K/Deblur/Anime4K_Deblur_DoG.glsl"
glsl-shaders-append="~~/shaders/SSimDownscaler.glsl"
