#!/bin/sh

KEYBIND_CLEAR=alt-0
KEYBIND_DELETE=alt-1

if [ "$1" = preview ]; then
    if echo "$2" | rg -vq '^\d+\t\[\[ binary data .*\]\]'; then
        echo "$2" | clipvault get
    elif echo "$2" | rg -vq '^\d+\t\[\[ binary data .*image.*\]\]'; then
        echo "$2" | cut -f2-
    else
        echo "$2" | clipvault get | chafa -f sixel -s "${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}"
    fi
    exit
fi

# fzf only allows searching against visible fields, so sad
# so I patched it with a rejected PR: https://github.com/nylvim/fzf
clipvault list \
    | npath fzf_clipboard_pinyin.py \
    | fzf -d $'\t' --nth 2.. --with-nth 2 --accept-nth ..2 \
        --preview "cb preview {}" --preview-window=up:67%:wrap \
        --expect "$KEYBIND_CLEAR,$KEYBIND_DELETE" \
    | {
        read -r key; read -r item
        case "$key" in
            "")
                echo "$item" | clipvault get | wl-copy;;
            "$KEYBIND_CLEAR")
                [ "$(echo $'No\nYes' | fzf --prompt "Clear? ")" = "Yes" ] && clipvault clear;;
            "$KEYBIND_DELETE")
                echo "$item" | head -1 | cut -f1 | clipvault delete; cb;;
        esac
    }
