#!/bin/sh

PREFIX="$HOME/.local/bin"
ARCH="x86_64-linux"
INDEX_URL="https://ziglang.org/download/index.json"
PREV_VERSION_FILE="$HOME/.cache/zig_dev_prev_version"

[ "$1" = "update" ] || { "$PREFIX/zig-dev/zig" "$@"; exit; }

cd "$PREFIX"
index=$(curl -fsSL "$INDEX_URL")

version="$(echo "$index" | jq -r .master.version)"
[ -f "$PREV_VERSION_FILE" ] \
    && [ "$version" = "$(cat "$PREV_VERSION_FILE")" ] \
    && { echo already up to date; exit; }

[ -d zig-dev ] && rm -rf zig-dev
mkdir zig-dev
file=$(echo "$index" | jq -r ".master[\"$ARCH\"].tarball")
curl -fL -C - "$file" -o zig-dev.tmp && {
    tar -xf zig-dev.tmp --strip-components 1 -C zig-dev
    rm -f zig-dev.tmp
    echo "$version" > "$PREV_VERSION_FILE"
}
