SUDO_EDITOR=vim
EDITOR=code-wait
VISUAL=code-wait
TERM=footclient
TERMINAL=footclient

all_proxy=http://127.0.0.1:7890
http_proxy=http://127.0.0.1:7890
https_proxy=http://127.0.0.1:7890

WINEPREFIX="$HOME/.wine"

ELECTRON_OZONE_PLATFORM_HINT=wayland
QT_QPA_PLATFORM=wayland
QT_QPA_PLATFORMTHEME=qt6ct

XMODIFIERS=@im=fcitx
# GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
QT_IM_MODULES='wayland;fcitx'

# LIBVA_DRIVER_NAME=iHD
ANV_DEBUG=video-decode,video-encode
